quan = int(input("จำนวนปืนทั้งหมด : "))
cost = int(input("ต้นทุนที่รับมา : "))
sell = int(input("ราคาที่นำไปขายต่อ : "))
team = int(input("จำนวนลูกน้องทั้งหมด : "))
print ("ต้นทุนทั้งหมด : ",(quan*cost))
print ("รายรับทั้งหมด : ",(quan*cost))
print ("กำไรสุทธิ : ",(quan*sell))
print ("เงินหักไปให้บอส : ",(20/100)*(quan*sell))
print ("เงินลูกน้องแต่ละคน : ",((20/100)*(quan*sell)/4))